### PR TITLE
💄 Add Navbar and Page

### PR DESCRIPTION
**Pull request by hikariatama**
Closes https://github.com/InnoTableTennis/score-scout-frontend/issues/10
Closes https://github.com/InnoTableTennis/score-scout-frontend/issues/8
Closes https://github.com/InnoTableTennis/score-scout-frontend/issues/14

### CODE REVIEW

**Review by andiazdi — DISMISSED** [review]
lgtm

**Review by MoriSummerz — APPROVED** [review]
lgtm

**Review by KekStroke — APPROVED** [review]
👍

**Comment by KekStroke** [comment]
image
Вот это если пофиксить будет вообще конфетка

**Pull request merged**
